### ISSUE TITLE
Specify hostname for port_check

### ISSUE THREAD

**Issue by saba0815** [kongo2002/nyx#1]
Feature request:
Configure a hostname or IP where the service is bound to when it is not bound to localhost to make the port_check work.

**Comment by kongo2002** [comment]
@saba0815 Thanks for the pointer - makes sense! You may try it out yourself by building from the current `master` sources.

I will package a new version in the near future as soon as I find some time.

Cheers,
Gregor

**Comment by saba0815** [comment]
Hi Gregor,
built it, used it, works! Thank you very much.
One thing tho: test_check_http fails during make check on the linux build machine.

Thx,
saba

**Comment by kongo2002** [comment]
@saba0815 Great to hear!

Are you by any chance able to reproduce? You may gladly open a new issue with the output of `make check`. That'd be great!

Cheers,
Gregor
