### ISSUE TITLE
test_check_http fails

### ISSUE THREAD

**Issue by saba0815** [kongo2002/nyx#2]
Executing _make check_ results in one test failing:
[nyx_make_check.log](https://github.com/kongo2002/nyx/files/2945340/nyx_make_check.log)

It was executed on CentOS 7.

Please request more environment stuff if you need.

Thx,
saba.

**Comment by kongo2002** [comment]
Thanks again for reporting!

It was a flaky test indeed - the HTTP test was implemented in a best-effort fashion that attempts to issue the HTTP checks against a local port 80 (if open). I suspect you had the port 80 open on your build machine.

The test is now disabled by default as the tests should not make any assumptions on their environment.

Cheers,
Gregor
