### ISSUE TITLE
Howto stop command

### ISSUE THREAD

**Issue by saba0815** [kongo2002/nyx#4]
Hi Gregor,
i tried to use the stop: command in my yaml but to no avail. To test it i used

> stop: echo test > $HOME/test.log

Am i missing something?

Thx, s.

**Comment by kongo2002** [comment]
Hi,
did you try wrapping that 'inline' shell command in a single executable script file? That should work for sure.

Cheers,
Gregor

**Comment by saba0815** [comment]
That was **it**. Many thanks man.

**Comment by kongo2002** [comment]
You're welcome!

I guess it should be stated more clearly in the documentation that the command has to be an executable and is not invoked in a shell itself.
