### ISSUE TITLE
Failed to connect to nyx

### ISSUE THREAD

**Issue by agido-malter** [kongo2002/nyx#5]
Hey man :)

From time to time, nyx loose himself that its running
OS: Amazon Linux 2 x86_64

:~/pushgateway $ ./nyx status all
[E] 2021-06-19T14:26:29 Failed to connect to nyx - the daemon is probably not running
[E] 2021-06-19T14:26:29 In local-mode make sure you are in the base directory or one of its sub directories

But its definitely running

: ~/pushgateway $ cat ~/.nyx/pid/nyx 
27849

:~/pushgateway $ ps x | grep nyx
11858 pts/0    S+     0:00 grep --color=auto nyx
27849 ?        Ssl    0:41 pushgateway/nyx -c pushgateway/nyx.yml
27850 ?        S      0:00 pushgateway/nyx -c pushgateway/nyx.yml

Do you have any idea or hint?

Greets Joerg

**Comment by agido-malter** [comment]
Issue was produced by ourself with auto cleanup /tmp

**Comment by kongo2002** [comment]
Hi, sorry for catching up so late but great you could solve the issue already :muscle: 

For anybody running into similar issue(s) a little bit of context:

Yes, the problem you describe can indeed be explained by dropping files in `/tmp`. By default nyx places its domain socket file (to communicate with the daemon process) at `/tmp/nyx.sock`. As soon as you delete that file nyx won't be able to contact the daemon anymore.

As of #6 I've added a new option `--socket` to have that socket file location to be configurable. Moreover I extended the error message to give a hint to that specific problem.

Cheers,
Gregor
